version: "3.7"

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    networks: 
      - tropikode-app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
    command: ["npx", "nodemon", "index.js"]

  wordpress:
    build: 
      context: wordpress
      dockerfile: Dockerfile
    networks:
      - tropikode-app
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 80:80
    command: ["apache2-foreground"]

networks:
  tropikode-app:
    driver: bridge